
[theme]
# use the light base theme
base="light"

# pick your accent color (hex)
primaryColor="#2587f0"

# optional: tweak backgrounds and text
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"

# choose a font: "sans serif", "serif" or "monospace"
font="sans serif"
